name: share_example
description: Demonstrates how to use the share plugin.

dependencies:
  flutter:
    sdk: flutter
  share:
    path: ../
  path_provider: any

flutter:
  uses-material-design: true
